<a href="https://colab.research.google.com/github/AndreyV80/NetStudy/blob/main/NumPyProjectWork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Задание 1**
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [ ]:
n = 10
x = np.arange(n)
x[::-1]      # 2-й вариант
# 1-й вариант, изначально представленный как решение
#sx = np.sort(x)[::-1]
#sx

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [2]:
n = 10
x = np.arange(n)
diag_x = np.diag(x[::-1], k=0)
diag_x
#np.trace(diag_x)   


array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [3]:
 # первоначальный вариант: после опытов со срезами матрицы, решил через цикл вывести значения диагоналей.
sum_x_diag_x = 0               
for i in range(n):
    sum_x_diag_x += diag_x[i][i]
print(sum_x_diag_x)
   

45


In [4]:
# по-гуглил немного -https://physics.susu.ru/vorontsov/language/numpy.html
np.trace(diag_x)          

45

**Задание 3**
Решите систему уравнений:
4x + 2y + z = 4; 
x + 3y = 12; 
5y + 4z = -3.

In [5]:
from numpy import linalg

In [6]:
a1 = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b1 = np.array([4, 12, -3])

In [7]:
linalg.solve(a1, b1)

array([ 0.46666667,  3.84444444, -5.55555556])

In [8]:
np.allclose( np.dot(a1, linalg.solve(a1, b1)), b1 )

True

**Задание 4**
В материалах занятия раздел “Задача 4 домашнего задания”

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [ ]:
from IPython.display import Image
Image("user_matrix.JPG")

Матрица в виде numpy array

In [10]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [11]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [14]:
qwerty = {}
id = 0
for i in users_stats:
    """ Расчет косинусного сходства нового клиента с клинтами из списка.
        Установление счетчика "id" для формирования словаря "qwerty".
        Вывод номера клиента и значения наиболее приближенного к новому клиенту
    """
    aLength = np.sqrt( (i*i).sum() )
    bLength = np.sqrt( (next_user_stats*next_user_stats).sum() )
    np.dot( i, next_user_stats ) / ( aLength * bLength ) 
    id += 1
    qwerty[id] = np.dot( i, next_user_stats ) / ( aLength * bLength )
for k_, v in qwerty.items():
     if v == max(qwerty.values()):
         print('ID - ', k_,';', 'Value - ', v)

ID -  8 ; Value -  0.9486832980505138


In [15]:
qwerty            # для проверки

{1: 0.19999999999999996,
 2: 0.8451542547285165,
 3: 0.3999999999999999,
 4: 0.7905694150420948,
 5: 0.3999999999999999,
 6: 0.0,
 7: 0.0,
 8: 0.9486832980505138,
 9: 0.0,
 10: 0.0}